* Tagged dynamic block for org-mode
[[https://melpa.org/#/org-tagged][https://melpa.org/packages/org-tagged-badge.svg]]
[[https://stable.melpa.org/#/org-tagged][https://stable.melpa.org/packages/org-tagged-badge.svg]]

Create a quick overview table over some tagged todos of your
org-files.

** Installation
To use this program, load org-tagged.el with =(require 'org-tagged)=.

** Usage
To create a tagged table for an org file, simply put the dynamic block
#+BEGIN_SRC
#+BEGIN: tagged :columns "%10tag1(Tag1)|tag2" :match "kanban"
#+END:
#+END_SRC
somewhere and run `C-c C-c' on it.
Alternative you can just run =org-tagged-initialize= which creates a
table similar to the former for you (please adjust the columns and
match expressions to your liking).

*** Columns format
The columns of the generated table are specified in the =:columns=
parameter:
- Columns are separated by =|=
- Each column follows the format =[%KLENGTH]TAG[(TITLE)]=
  - Only TAG is required
  - LENGTH defaults to 1000 if not specified
  - TITLE defaults to TAG if not specified

** Development
You can easily run this package locally. Commits should be checked
with =rake test= which in turn pulls up a container with the default
environment (ATM the container is always rebuilt for changes on the
project as all files are used from inside the container (bindmount
problems with podman + osx).
